import {Activity, Artist, Post} from "@/lib/mock-types";

export const userPosts: Post[] = [
    {
        content: "New EP 'Techno Dimensions' out now! 🎵 #NewRelease",
        time: "2 hours ago",
        likes: 87,
        comments: 14,
        image: "/images/dj-mixer.png",
    },
];

export const allActivity: Activity[] = [
    {
        id: "a1",
        type: "purchase",
        name: "Banger",
        avatar: "/avatars/banger.jpg",
        action: "bought your tokens",
        message: "Love your latest track!",
        amount: 15,
        time: "5 minutos atrás",
        artistId: "banger",
        tokenName: "JUAMPI",
        relatedTo: "artist",
    },
    {
        id: "a2",
        type: "mention",
        name: "Nicola Marti",
        avatar: "/avatars/nicola.jpg",
        action: "mentioned you in a comment",
        message: "@iamjuampi could have ideas for this remix.",
        time: "15 minutos atrás",
        artistId: "nicolamarti",
        tokenName: "NICOLA",
        relatedTo: "artist",
    },
    {
        id: "a3",
        type: "purchase",
        name: "AXS",
        avatar: "/avatars/axs.jpg",
        action: "bought your tokens",
        amount: 25,
        time: "30 minutos atrás",
        artistId: "axs",
        tokenName: "JUAMPI",
        relatedTo: "artist",
    },
    {
        id: "a4",
        type: "reward",
        name: "Drops",
        avatar: "/avatars/dropsland-logo-square.png",
        action: "gave you a reward for your activity",
        message: "100 followers! Here's 5 $DROPS.",
        amount: 5,
        time: "2 horas atrás",
        artistId: "dropsland",
        tokenName: "DROPS",
        relatedTo: "artist",
    },
    {
        id: "a5",
        type: "mention",
        name: "FLUSH",
        avatar: "/avatars/flush.jpg",
        action: "mentioned you in a post",
        message: "Learning from @iamjuampi's tutorials.",
        time: "3 horas atrás",
        artistId: "flush",
        tokenName: "FLUSH",
        relatedTo: "artist",
    },
    {
        id: "a6",
        type: "purchase",
        name: "Kr4D",
        avatar: "/avatars/kr4d.jpg",
        action: "bought your tokens",
        message: "For your next release!",
        amount: 10,
        time: "5 horas atrás",
        artistId: "kr4d",
        tokenName: "JUAMPI",
        relatedTo: "artist",
    },
    // Actividades para fans
    {
        id: "f1",
        type: "reward",
        name: "Banger",
        avatar: "/avatars/banger.jpg",
        action: "released a new reward for followers",
        message: "Exclusive track for token holders!",
        time: "1 hora atrás",
        artistId: "banger",
        tokenName: "BANGER",
        relatedTo: "fan",
    },
    {
        id: "f2",
        type: "mention",
        name: "iamjuampi",
        avatar: "/avatars/juampi.jpg",
        action: "posted a new track",
        message: "New EP 'Techno Dimensions' out now!",
        time: "3 horas atrás",
        artistId: "iamjuampi",
        tokenName: "JUAMPI",
        relatedTo: "fan",
    },
    {
        id: "f3",
        type: "follow",
        name: "Nicola Marti",
        avatar: "/avatars/nicola.jpg",
        action: "announced an upcoming event",
        message: "Playing at Club Underground this weekend!",
        time: "1 día atrás",
        artistId: "nicolamarti",
        tokenName: "NICOLA",
        relatedTo: "fan",
    },
    {
        id: "f4",
        type: "reward",
        name: "AXS",
        avatar: "/avatars/axs.jpg",
        action: "released a new production tutorial",
        message: "Exclusive sound design tutorial available.",
        time: "2 días atrás",
        artistId: "axs",
        tokenName: "AXS",
        relatedTo: "fan",
    },
]

export const allArtists: Artist[] = [
    {
        id: "iamjuampi",
        name: "iamjuampi",
        handle: "@iamjuampi",
        avatar: "/avatars/juampi.jpg",
        coverImage: "/images/bdeeeee.jpg",
        genre: "Tech-House",
        description: "DJ, producer, and founder of the record label Best Drops Ever.",
        supporters: 1850,
        blgReceived: 1850,
        featured: true,
        tokenName: "JUAMPI",
        tokenPrice: 0.45,
        posts: [
            {
                content: "Just released my new EP 'Techno Dimensions'. Available now on all platforms! #TechnoDimensions #NewRelease",
                time: "2 hours ago",
                likes: 87,
                comments: 14,
                image: "/images/dj-mixer.png",
            },
            {
                content: "Preparing my set for this weekend at Club Underground. It's going to be an epic night of techno and house. Who's coming? 🎧",
                time: "1 day ago",
                likes: 65,
                comments: 23,
            },
            {
                content: "Happy to announce I'll be playing at the Electronic Dreams festival next month. See you there! #ElectronicDreams #Festival",
                time: "3 days ago",
                likes: 112,
                comments: 31,
                image: "/images/dj-mixer.png",
            },
            {
                content: "Working on new sounds for my upcoming release. I'm experimenting with analog synthesizers and 90s samples.",
                time: "1 week ago",
                likes: 94,
                comments: 17,
            },
        ],
        exclusiveContent: [
            {
                title: "Exclusive track - Midnight Pulse (Extended Mix)",
                description: "10-minute extended version only for $JUAMPI holders",
                date: "Mar 15, 2025",
            },
            {
                title: "Production tutorial - Techno Kicks",
                description: "Learn to create powerful kicks for your techno tracks",
                date: "Mar 10, 2025",
            },
            {
                title: "Live set - Club Underground",
                description: "Complete recording of my latest set at Club Underground",
                date: "Mar 5, 2025",
            },
        ],
        rewards: [
            {
                title: "Exclusive Monthly Track",
                description: "Unreleased track available only to token holders",
                minTokens: 10,
                subscribers: 156,
            },
            {
                title: "Production Masterclass",
                description: "Monthly video tutorial on advanced production techniques",
                minTokens: 25,
                subscribers: 87,
            },
            {
                title: "Stems & Project Files",
                description: "Complete project files for selected tracks",
                minTokens: 50,
                subscribers: 42,
            },
            {
                title: "VIP Club Access",
                description: "Priority access to my shows at Club Underground",
                minTokens: 75,
                subscribers: 28,
            },
        ],
        certifications: [
            {
                id: "c1",
                type: "gold",
                title: "Gold Record",
                description: "Techno Dimensions EP reached 500,000 streams",
                date: "Mar 15, 2025",
            },
            {
                id: "c2",
                type: "platinum",
                title: "Platinum Record",
                description: "Midnight Pulse single reached 1,000,000 streams",
                date: "Feb 20, 2025",
            },
            {
                id: "c3",
                type: "views",
                title: "1M Views",
                description: "Music video for 'Electronic Dreams' reached 1 million views",
                date: "Jan 30, 2025",
            },
            {
                id: "c4",
                type: "soldout",
                title: "Sold Out Event",
                description: "Club Underground performance sold out in 24 hours",
                date: "Jan 15, 2025",
            },
            {
                id: "c5",
                type: "award",
                title: "Best New Artist",
                description: "Electronic Music Awards 2025",
                date: "Jan 5, 2025",
            },
        ],
    },
    {
        id: "banger",
        name: "Banger",
        handle: "@banger",
        avatar: "/avatars/banger.jpg",
        coverImage: "/images/bdeeeee.jpg",
        genre: "DNB y Tech-House",
        description: "House producer with disco and funk influences. Known for energetic rhythms.",
        supporters: 2100,
        blgReceived: 2100,
        featured: true,
        tokenName: "BANGER",
        tokenPrice: 0.42,
        posts: [
            {
                content: "Just dropped 'Disco Inferno' - my funkiest house track yet! Link in bio 🔥 #DiscoHouse #NewMusic",
                time: "3 hours ago",
                likes: 92,
                comments: 18,
                image: "/images/dj-mixer.png",
            },
            {
                content: "Vinyl lovers! Limited edition 12\" of 'Groove Machine' coming next week. Only 200 copies available!",
                time: "1 day ago",
                likes: 124,
                comments: 35,
            },
            {
                content: "Throwback to my Ibiza set last summer. Still can't believe how amazing that crowd was! #Ibiza #HouseMusic",
                time: "3 days ago",
                likes: 156,
                comments: 27,
                image: "/images/dj-mixer.png",
            },
            {
                content: "Studio session with @nicolamarti today. The collab you've all been waiting for is finally happening!",
                time: "5 days ago",
                likes: 187,
                comments: 42,
            },
        ],
        exclusiveContent: [
            {
                title: "Exclusive track - Disco Fever (Club Mix)",
                description: "Extended club mix only for $BANGER holders",
                date: "Mar 12, 2025",
            },
            {
                title: "Sample pack - House Essentials Vol. 1",
                description: "Collection of premium samples for house producers",
                date: "Mar 5, 2025",
            },
            {
                title: "Behind the scenes - Studio Session",
                description: "Watch how I created my latest track from scratch",
                date: "Feb 28, 2025",
            },
        ],
        rewards: [
            {
                title: "Disco House Sample Pack",
                description: "Monthly collection of disco samples and loops",
                minTokens: 15,
                subscribers: 178,
            },
            {
                title: "Vinyl First Access",
                description: "Early access to limited vinyl releases",
                minTokens: 30,
                subscribers: 92,
            },
            {
                title: "Remix Competition",
                description: "Exclusive stems to remix my tracks monthly",
                minTokens: 45,
                subscribers: 64,
            },
            {
                title: "DJ Feedback",
                description: "Personal feedback on your tracks once a month",
                minTokens: 75,
                subscribers: 38,
            },
        ],
        certifications: [
            {
                id: "c1",
                type: "gold",
                title: "Gold Record",
                description: "Disco Inferno single reached 500,000 streams",
                date: "Feb 10, 2025",
            },
            {
                id: "c2",
                type: "views",
                title: "2M Views",
                description: "Music video for 'Groove Machine' reached 2 million views",
                date: "Jan 25, 2025",
            },
            {
                id: "c3",
                type: "soldout",
                title: "Sold Out Tour",
                description: "European Summer Tour 2024 sold out in 48 hours",
                date: "Dec 15, 2024",
            },
            {
                id: "c4",
                type: "award",
                title: "Best House Producer",
                description: "DJ Mag Awards 2024",
                date: "Nov 20, 2024",
            },
        ],
    },
    {
        id: "nicolamarti",
        name: "Nicola Marti",
        handle: "@nicolamarti",
        avatar: "/avatars/nicola.jpg",
        coverImage: "/images/bdeeeee.jpg",
        genre: "Tech-House",
        description: "Italian melodic techno artist with a unique and atmospheric style.",
        supporters: 1750,
        blgReceived: 1750,
        featured: true,
        tokenName: "NICOLA",
        tokenPrice: 0.38,
        posts: [
            {
                content: "My new album 'Ethereal Landscapes' is finally complete. Can't wait to share this journey with you all next month.",
                time: "5 hours ago",
                likes: 143,
                comments: 38,
                image: "/images/dj-mixer.png",
            },
            {
                content: "Recording strings with the Milano Chamber Orchestra today. Adding classical elements to electronic music is pure magic.",
                time: "2 days ago",
                likes: 167,
                comments: 29,
            },
            {
                content: "Berlin, thank you for an unforgettable night at Panorama Bar. The energy was transcendent. #Berlin #MelodicTechno",
                time: "4 days ago",
                likes: 201,
                comments: 47,
                image: "/images/dj-mixer.png",
            },
            {
                content: "Just finished mastering the collaboration with @banger - two different worlds colliding in the most beautiful way.",
                time: "1 week ago",
                likes: 178,
                comments: 35,
            },
        ],
        exclusiveContent: [
            {
                title: "Exclusive track - Melodic Journey (Extended Mix)",
                description: "10-minute journey through melodic techno landscapes",
                date: "Mar 14, 2025",
            },
            {
                title: "Ableton Live Template - Melodic Techno",
                description: "My personal template for creating melodic techno tracks",
                date: "Mar 7, 2025",
            },
            {
                title: "Live recording - Club Panorama Berlin",
                description: "Full 2-hour set from my recent Berlin performance",
                date: "Feb 25, 2025",
            },
        ],
        rewards: [
            {
                title: "Orchestral Elements",
                description: "Monthly orchestral samples recorded with live musicians",
                minTokens: 15,
                subscribers: 145,
            },
            {
                title: "Ambient Soundscapes",
                description: "Exclusive ambient compositions for meditation",
                minTokens: 25,
                subscribers: 78,
            },
            {
                title: "Melodic Progression Masterclass",
                description: "Monthly tutorial on creating emotional progressions",
                minTokens: 40,
                subscribers: 52,
            },
            {
                title: "Studio Live Stream",
                description: "Monthly live stream from my Milan studio",
                minTokens: 60,
                subscribers: 31,
            },
        ],
        certifications: [
            {
                id: "c1",
                type: "platinum",
                title: "Platinum Record",
                description: "Ethereal Landscapes album reached 1,000,000 streams",
                date: "Mar 5, 2025",
            },
            {
                id: "c2",
                type: "award",
                title: "Best Melodic Techno Artist",
                description: "International Electronic Music Awards 2024",
                date: "Dec 10, 2024",
            },
            {
                id: "c3",
                type: "soldout",
                title: "Sold Out Show",
                description: "Milan Techno Festival headlining show sold out",
                date: "Nov 20, 2024",
            },
            {
                id: "c4",
                type: "views",
                title: "3M Views",
                description: "Live performance at Tomorrowland reached 3 million views",
                date: "Oct 15, 2024",
            },
        ],
    },
    {
        id: "axs",
        name: "AXS",
        handle: "@axs",
        avatar: "/avatars/axs.jpg",
        coverImage: "/images/bdeeeee.jpg",
        genre: "Riddim",
        description: "Producer of industrial techno with influences from EBM and post-punk.",
        supporters: 1680,
        blgReceived: 1680,
        featured: true,
        tokenName: "AXS",
        tokenPrice: 0.4,
        posts: [
            {
                content: "New EP 'Mechanical Dystopia' drops next week. The darkest, hardest techno I've ever made. #IndustrialTechno",
                time: "6 hours ago",
                likes: 132,
                comments: 41,
                image: "/images/dj-mixer.png",
            },
            {
                content: "Field recording session at an abandoned factory today. These machines make the most incredible sounds.",
                time: "2 days ago",
                likes: 98,
                comments: 23,
            },
            {
                content: "My modular synth setup is finally complete. Spent 3 years building this beast. Time to make some noise!",
                time: "5 days ago",
                likes: 176,
                comments: 52,
                image: "/images/dj-mixer.png",
            },
            {
                content: "Berghain closing set was pure madness last night. 4 hours of relentless industrial techno. Thank you Berlin!",
                time: "1 week ago",
                likes: 215,
                comments: 67,
            },
        ],
        exclusiveContent: [
            {
                title: "Exclusive track - Industrial Complex (Extended Mix)",
                description: "Hard-hitting industrial techno journey",
                date: "Mar 10, 2025",
            },
            {
                title: "Sound design tutorial - Creating industrial textures",
                description: "Learn how I create my signature industrial sounds",
                date: "Mar 3, 2025",
            },
            {
                title: "Modular patches collection",
                description: "My favorite modular synth patches for techno production",
                date: "Feb 20, 2025",
            },
        ],
        rewards: [
            {
                title: "Modular Synth Patches",
                description: "Monthly collection of my modular synth patches",
                minTokens: 20,
                subscribers: 132,
            },
            {
                title: "Industrial Sound Design",
                description: "Tutorials on creating harsh industrial sounds",
                minTokens: 35,
                subscribers: 85,
            },
            {
                title: "Field Recording Library",
                description: "Access to my industrial field recording library",
                minTokens: 50,
                subscribers: 47,
            },
            {
                title: "Hardware Processing Techniques",
                description: "Learn how I process sounds through hardware",
                minTokens: 75,
                subscribers: 29,
            },
        ],
        certifications: [
            {
                id: "c1",
                type: "gold",
                title: "Gold Record",
                description: "Mechanical Dystopia EP reached 500,000 streams",
                date: "Feb 15, 2025",
            },
            {
                id: "c2",
                type: "views",
                title: "1.5M Views",
                description: "Berghain live set reached 1.5 million views",
                date: "Jan 20, 2025",
            },
            {
                id: "c3",
                type: "award",
                title: "Best Industrial Techno Producer",
                description: "Underground Electronic Awards 2024",
                date: "Dec 5, 2024",
            },
            {
                id: "c4",
                type: "soldout",
                title: "Sold Out Warehouse Event",
                description: "Industrial Noise warehouse event sold out in 2 hours",
                date: "Nov 10, 2024",
            },
        ]
    },
    {
        id: "flush",
        name: "FLUSH",
        handle: "@flush",
        avatar: "/avatars/flush.jpg",
        coverImage: "/images/bdeeeee.jpg",
        genre: "Dubstep",
        description: "Productor de drum & bass con un enfoque en sonidos futuristas y experimentales.",
        supporters: 1320,
        blgReceived: 1320,
        featured: false,
        tokenName: "FLUSH",
        tokenPrice: 0.35,
        posts: [],
        exclusiveContent: [],
        rewards: [],
        certifications: []
    },
    {
        id: "danilodr",
        name: "DaniløDR",
        handle: "@daniloDR",
        avatar: "/avatars/danilo.jpg",
        coverImage: "/images/bdeeeee.jpg",
        genre: "Trap",
        description: "Creador de trance progresivo con elementos de música clásica y ambient.",
        supporters: 980,
        blgReceived: 980,
        featured: false,
        tokenName: "DANILO",
        tokenPrice: 0.30,
        posts: [],
        exclusiveContent: [],
        rewards: [],
        certifications: []
    },
    {
        id: "spitflux",
        name: "Spitflux",
        handle: "@spitflux",
        avatar: "/avatars/spitflux.jpg",
        coverImage: "/images/bdeeeee.jpg",
        genre: "Dubstep",
        description: "Innovador en la escena dubstep con un estilo agresivo y detallado.",
        supporters: 1450,
        blgReceived: 1450,
        featured: false,
        tokenName: "SPIT",
        tokenPrice: 0.32,
        posts: [],
        exclusiveContent: [],
        rewards: [],
        certifications: []
    },
    {
        id: "kr4d",
        name: "Kr4D",
        handle: "@kr4d",
        avatar: "/avatars/kr4d.jpg",
        coverImage: "/images/bdeeeee.jpg",
        genre: "Electro",
        description: "Artista de ambient y música experimental con enfoque en paisajes sonoros inmersivos.",
        supporters: 890,
        blgReceived: 890,
        featured: false,
        tokenName: "KR4D",
        tokenPrice: 0.28,
        posts: [],
        exclusiveContent: [],
        rewards: [],
        certifications: []
    },
]
